// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: api/v1/chunk.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChunkClient is the client API for Chunk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkClient interface {
	// 创建一次上传
	CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadReply, error)
	// 针对一次上传对象来上传分片内容
	UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkReply, error)
	// 上传完成
	DoneUpload(ctx context.Context, in *DoneUploadRequest, opts ...grpc.CallOption) (*DoneUploadReply, error)
	// 检查文件是否存在
	CheckFileExists(ctx context.Context, in *CheckFileExistRequest, opts ...grpc.CallOption) (*CheckFileExistReply, error)
	// 检查分片是否存在
	CheckChunkExists(ctx context.Context, in *CheckChunkExistsRequest, opts ...grpc.CallOption) (*CheckChunkExistsReply, error)
}

type chunkClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkClient(cc grpc.ClientConnInterface) ChunkClient {
	return &chunkClient{cc}
}

func (c *chunkClient) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadReply, error) {
	out := new(CreateUploadReply)
	err := c.cc.Invoke(ctx, "/api.v1.Chunk/CreateUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkClient) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkReply, error) {
	out := new(UploadChunkReply)
	err := c.cc.Invoke(ctx, "/api.v1.Chunk/UploadChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkClient) DoneUpload(ctx context.Context, in *DoneUploadRequest, opts ...grpc.CallOption) (*DoneUploadReply, error) {
	out := new(DoneUploadReply)
	err := c.cc.Invoke(ctx, "/api.v1.Chunk/DoneUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkClient) CheckFileExists(ctx context.Context, in *CheckFileExistRequest, opts ...grpc.CallOption) (*CheckFileExistReply, error) {
	out := new(CheckFileExistReply)
	err := c.cc.Invoke(ctx, "/api.v1.Chunk/CheckFileExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkClient) CheckChunkExists(ctx context.Context, in *CheckChunkExistsRequest, opts ...grpc.CallOption) (*CheckChunkExistsReply, error) {
	out := new(CheckChunkExistsReply)
	err := c.cc.Invoke(ctx, "/api.v1.Chunk/CheckChunkExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServer is the server API for Chunk service.
// All implementations must embed UnimplementedChunkServer
// for forward compatibility
type ChunkServer interface {
	// 创建一次上传
	CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadReply, error)
	// 针对一次上传对象来上传分片内容
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkReply, error)
	// 上传完成
	DoneUpload(context.Context, *DoneUploadRequest) (*DoneUploadReply, error)
	// 检查文件是否存在
	CheckFileExists(context.Context, *CheckFileExistRequest) (*CheckFileExistReply, error)
	// 检查分片是否存在
	CheckChunkExists(context.Context, *CheckChunkExistsRequest) (*CheckChunkExistsReply, error)
	mustEmbedUnimplementedChunkServer()
}

// UnimplementedChunkServer must be embedded to have forward compatible implementations.
type UnimplementedChunkServer struct {
}

func (UnimplementedChunkServer) CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUpload not implemented")
}
func (UnimplementedChunkServer) UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadChunk not implemented")
}
func (UnimplementedChunkServer) DoneUpload(context.Context, *DoneUploadRequest) (*DoneUploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoneUpload not implemented")
}
func (UnimplementedChunkServer) CheckFileExists(context.Context, *CheckFileExistRequest) (*CheckFileExistReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFileExists not implemented")
}
func (UnimplementedChunkServer) CheckChunkExists(context.Context, *CheckChunkExistsRequest) (*CheckChunkExistsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckChunkExists not implemented")
}
func (UnimplementedChunkServer) mustEmbedUnimplementedChunkServer() {}

// UnsafeChunkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServer will
// result in compilation errors.
type UnsafeChunkServer interface {
	mustEmbedUnimplementedChunkServer()
}

func RegisterChunkServer(s grpc.ServiceRegistrar, srv ChunkServer) {
	s.RegisterService(&Chunk_ServiceDesc, srv)
}

func _Chunk_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Chunk/CreateUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServer).CreateUpload(ctx, req.(*CreateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chunk_UploadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServer).UploadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Chunk/UploadChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServer).UploadChunk(ctx, req.(*UploadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chunk_DoneUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServer).DoneUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Chunk/DoneUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServer).DoneUpload(ctx, req.(*DoneUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chunk_CheckFileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServer).CheckFileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Chunk/CheckFileExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServer).CheckFileExists(ctx, req.(*CheckFileExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chunk_CheckChunkExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckChunkExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServer).CheckChunkExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Chunk/CheckChunkExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServer).CheckChunkExists(ctx, req.(*CheckChunkExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chunk_ServiceDesc is the grpc.ServiceDesc for Chunk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chunk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Chunk",
	HandlerType: (*ChunkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUpload",
			Handler:    _Chunk_CreateUpload_Handler,
		},
		{
			MethodName: "UploadChunk",
			Handler:    _Chunk_UploadChunk_Handler,
		},
		{
			MethodName: "DoneUpload",
			Handler:    _Chunk_DoneUpload_Handler,
		},
		{
			MethodName: "CheckFileExists",
			Handler:    _Chunk_CheckFileExists_Handler,
		},
		{
			MethodName: "CheckChunkExists",
			Handler:    _Chunk_CheckChunkExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/chunk.proto",
}
