// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kylin-uploader/internal/biz"
	"kylin-uploader/internal/conf"
	"kylin-uploader/internal/data"
	"kylin-uploader/internal/server"
	"kylin-uploader/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	chunkRepo := data.NewChunkRepo(dataData, logger)
	chunkUsecase := biz.NewChunkUsecase(chunkRepo, logger)
	chunkService := service.NewChunkService(chunkUsecase)
	grpcServer := server.NewGRPCServer(confServer, chunkService, logger)
	httpServer := server.NewHTTPServer(confServer, chunkService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
